schema: "classroom50/repo-config/v1"
classroom: "ds212"
assignment: "portfolio"
owner:
  username: "josaputra15"
  id: 144293233
  accepted_at: "2026-09-09T16:30:13Z"
source:
  owner: "mac-ds212-f26"
  owner_id: 323652586
  repo: "portfolio-template"
  branch: "main"
